/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StencilVirtualScrolling {
    /**
    * Fixed height of rows
    */
    'rowHeight': number;
    /**
    * function for rendering different type of lists/rows
    */
    'rowRenderer': (rowStyles, fromRow: number, toRow: number, parentStyles) => any;
    /**
    * for now, only fixed height rows can be rendered in the component
    */
    'rowsLength': number;
    /**
    * Height of the container that would remain visible
    */
    'scrollContainerHeight': number;
  }
  interface VirtualScrollingDemo {}
}

declare global {


  interface HTMLStencilVirtualScrollingElement extends Components.StencilVirtualScrolling, HTMLStencilElement {}
  var HTMLStencilVirtualScrollingElement: {
    prototype: HTMLStencilVirtualScrollingElement;
    new (): HTMLStencilVirtualScrollingElement;
  };

  interface HTMLVirtualScrollingDemoElement extends Components.VirtualScrollingDemo, HTMLStencilElement {}
  var HTMLVirtualScrollingDemoElement: {
    prototype: HTMLVirtualScrollingDemoElement;
    new (): HTMLVirtualScrollingDemoElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-virtual-scrolling': HTMLStencilVirtualScrollingElement;
    'virtual-scrolling-demo': HTMLVirtualScrollingDemoElement;
  }
}

declare namespace LocalJSX {
  interface StencilVirtualScrolling {
    /**
    * Fixed height of rows
    */
    'rowHeight'?: number;
    /**
    * function for rendering different type of lists/rows
    */
    'rowRenderer'?: (rowStyles, fromRow: number, toRow: number, parentStyles) => any;
    /**
    * for now, only fixed height rows can be rendered in the component
    */
    'rowsLength'?: number;
    /**
    * Height of the container that would remain visible
    */
    'scrollContainerHeight'?: number;
  }
  interface VirtualScrollingDemo {}

  interface IntrinsicElements {
    'stencil-virtual-scrolling': StencilVirtualScrolling;
    'virtual-scrolling-demo': VirtualScrollingDemo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'stencil-virtual-scrolling': LocalJSX.StencilVirtualScrolling & JSXBase.HTMLAttributes<HTMLStencilVirtualScrollingElement>;
      'virtual-scrolling-demo': LocalJSX.VirtualScrollingDemo & JSXBase.HTMLAttributes<HTMLVirtualScrollingDemoElement>;
    }
  }
}


